- name: Create a user with sudo privileges
  hosts: all
  gather_facts: no
  become: yes
  vars:
    user: 'marizaga'

  tasks:
    - name: Include vars for passwd
      include_vars:
        name: secrets
        file: secrets.yml

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add user to wheel group
      user:
        name: "{{user}}"
        groups: wheel
        append: yes
        state: present
        createhome: yes
        password: "{{ secrets.ubuntu_2_marizaga_passwd }}"

# debug
# ansible-playbook create_sudoer_user.yml -i inventory -l ubuntu_2 -v