---
- name: playbook for install nginx
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: apt update
      package:
        update_cache: yes

    - name: apt install nginx
      package:
        name:
          - nginx
        state: present
        update_cache: yes
      register: install_nginx_output

    - name: Start service nginx, if not started
      service:
        name: nginx
        state: started