- name: playbook for install nginx
  hosts: all
  gather_facts: no
  become: yes
#  become_user: marizaga

  tasks:
    - name: apt update
      package:
        update_cache: yes

    - name: apt install nginx
      package:
        name:
          - nginx
        state: present
      register: install_nginx_output

    - name: Start service nginx, if not started
      service:
        name: nginx
        state: started

# command
# ansible-playbook install_nginx.yml -i inventory -l ubuntu_2 -v