---
- name: playbook for install nginx
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
#    ansible_python_interpreter: "/usr/bin/python3"
# https://www.nginx.com/blog/setting-up-nginx/
# https://medium.com/analytics-vidhya/dajngo-with-nginx-gunicorn-aaf8431dc9e0:
  tasks:
    - name: apt update
      package:
        update_cache: yes

    - name: apt install nginx
      package:
        name:
          - nginx
        state: present
        update_cache: yes
      register: install_nginx_output

#    - name: install nginx with shell
#      shell: sudo apt install nginx

    - name: Start service nginx, if not started
      service:
        name: nginx
        state: started