---

- name: "Test for install nginx on {{linux_cinnamon}}"
  hosts: linux_cinnamon
  gather_facts: no
  vars:
      my_order: "{{ order }}"
#  become: yes
#  become_user: root

  tasks:
    - name: este es el primer bloque
      block:
      - name: ensure the remote hosts is reachable
        ping:
        register: ping_out
      - debug:
          msg: "{{ping_out}}"
      rescue:
        - name: the rescue block
          debug:
             msg: 'Se ha ejecutado el rescue block'
#    - name: este es el segundo bloque
#      block:
#        - name: this is the second block
#          command: /bin/echo block 2 working
#          register: command_out
#        - name: debugging the output
#          debug:
#            msg: "{{command_out}}
#      rescue:
#          - name: the rescue block2
#            debug:
#              msg: 'Se ha ejecutado el rescue block2'

#    - name: apt install nginx
#      apt:
#        name: nginx
#        state: present
#      register: apt_output
#
#    - name: Remove dependencies that are no longer required
#      apt:
#        autoremove: yes
#
#    - debug:
#        msg: apt_output