- name: playbook for install venv
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: install python3-venv
      package:
        name:
          - python3-venv
          - python3.8-venv
        state: present
      register: install_python3_venv_output

    - name: create virtual env
      shell: python3.8 -m venv /opt/python38_venv

# command
# ansible-playbook install_venv.yml -i inventory -l ubuntu_2 -v