---
- name: playbook to check conectivity
  hosts: all
  gather_facts: yes

  tasks:
      - name: ensure the remote hosts is reachable
        ping:
        register: ping_out

      - debug:
          msg: "{{ansible_facts}}"
