- name: playbook for start the app
  hosts: all
  gather_facts: no
#  become: yes
  vars_files:
    - secrets.yml
  vars:
    remote_dir_for_app: /opt/Django_project
    virtualenv_dir: /opt/python38_venv
  environment:
    SECRET: "{{ secret_key }}"

  tasks:
    - name: run migrate
      command:
        cmd: /opt/python38_venv/bin/python /opt/Django_project/manage.py migrate
        creates: db.sqlite3
      register: migrate_output

#    - name: run dev server on localhost
#      command:
#        cmd: /opt/python38_venv/bin/python /opt/Django_project/manage.py runserver
##      async: 20
##      poll: 5
#      register: run_server_output

#    - name: check dev server started
#      fail:
#        msg: "the dev server did not started, review config"
#      when: '"Starting development server at" not in run_server_output.stdout'

    - name: Create dir for static files
      command:
        cmd: "{{ item }}"
      loop:
        - mkdir -p /var/www/inicioms.com/static
        - chown -R ubuntu:ubuntu /var/www/inicioms.com
      become: yes

    - name: Collect static files for the app
      command:
        cmd: /opt/python38_venv/bin/python /opt/Django_project/manage.py collectstatic

#    - name: Create super user for the app
#      community.general.django_manage:
#        command: "createsuperuser --noinput --username=marizaga --email=marceloarizagaforonda@gmail.com"
#        app_path: "{{ remote_dir_for_app }}"
#        virtualenv: "{{ virtualenv_dir }}"

#    - name: Start the App on develop server
#      async: 60
#      poll: 10
#      shell: "(. {{ virtualenv_dir }}/bin/activate && python3.8 manage.py runserver)"
#      args:
#        chdir: "{{ remote_dir_for_app }}"
#      register: start_app_output
#
#    - name: Validating the port is open
#      tags: check_dev_server
#      wait_for:
#        host: "localhost"
#        port: 8000
#        delay: 10
#        timeout: 30
#        state: started
#        msg: "Django-dev-server is not running"

# command
# ansible-playbook start_the_app.yml -i inventory -l ubuntu_2 -v