---
- name: playbook to train with dicts
  hosts: localhost
  gather_facts: no


  tasks:
#    - set_fact:
#        padres: [{"name":'Marcelo', "surname":'Arizaga', "hijos":[]},{"name":'tina', "surname":'salazar', "hijos":[]}]
#        hijos: [{"name":'Marcos', "surname":'Arizaga', "position":1}, {"name":'Amelie', "surname":'Arizaga', "position":2}]
#
#    - set_fact:
#        padre_y_hijos_lista: "{{ padres | map('combine',{'hijos':hijos} )| list }}"
#
#    - shell: echo "{{ padres | to_json }}" > padres.json
#    - shell: echo "{{ hijos | to_json }}" > hijos.json
    - name: give me list combo of two lists
      debug:
        msg: "{{ [1,2,3,4,5] | zip(['a','b','c','d','e','f']) | list  }}"

    - name: give me longest combo of three lists , fill with X
      debug:
        msg: "{{ [1,2,3] | zip_longest(['a','b','c','d','e','f'], [21, 22, 23], fillvalue='X') | list }}"


